heewon1234/daebbang_react

src/App.js
=> CS-11 리액트 지라 연동 테스트

package-lock.json, package.json
=> bootstrap, reactstrap install

src/pages/Admin/AdminMain.js, src/pages/EstateManage/EstateCreate.js, src/pages/LoadEstate/LoadEstate.js, src/pages/Login/Login.js, src/pages/main/main.js
=> NG-45 페이지 폴더 생성

src/App.js, src/pages/Admin/AdminMain.js, src/pages/commons/TopForm.js, src/pages/main/main.js
라우터를 이용해 app.js를 만들었습니다. topform 폴더를 만들었고 나머지는 export를 추가하였습니다.
=> NG-45 app.js 수정

src/App.js, src/pages/Board/Board.js, src/pages/EstateManage/EstateCreate.js, src/pages/LoadEstate/LoadEstate.js
=> NG-11 app.js 라우터 수정

src/App.js, src/pages/Login/Login.js, src/pages/Login/Login.module.css
=> login import

src/pages/Login/Login.js, src/pages/Login/Login.module.css
=> NG-25 login design update

src/pages/commons/TopForm.module.css
topform이 bodyform에 가려지는 오류를 수정했습니다.
메뉴버튼이 bodyform에 가려지는 오류를 수정했습니다.
=> topform 수정

src/pages/commons/TopForm.js
topform에 관리자페이지로 가는 경로가 추가되었습니다.
=> topform 관리자페이지 추가

src/pages/Login/Login.js
=> NG-51 login update

src/pages/Home/Home.js, src/pages/commons/TopForm.js, src/pages/commons/TopForm.module.css
topform 오른쪽 버튼들이 세로로 있던 오류를 수정하였습니다.
원룸으로 이동하는 경로를 추가하였습니다.
=> topform ui 및 경로 수정

src/App.js, src/pages/Login/Login.js, src/pages/Login/Login.module.css, src/pages/SignUp/SignUp.js
=> NG-26 signUp create

package-lock.json, package.json, src/App.js, src/pages/EstateManage/EstateCreate.js, src/pages/EstateManage/css/EstateCreate.module.css, src/pages/EstateManage/css/Post.module.css, src/pages/EstateManage/js/EstateCreate1.js, src/pages/EstateManage/js/Post.js
주소 입력을 위해 react-daum-postcode 추가했습니다
npm install 한 번 씩 해주세요
EstateManage/js/
EstateManage/css/
폴더 생성
EstateManage/EstateCreate.js를
EstateManage/js로 옮기고 파일명을 EstateCreate1.js으로 변경
(이후에 2~5로 늘어날 예정입니다.)
우편번호 찾기 버튼을 눌렀을 때 API 출력할 Post.js 추가
폴더 변경에 맞춰서 App.js의 링크 수정
css 파일 추가
=> NG-46 <임시 프론트 생성>

src/pages/Login/Login.js, src/pages/Main/Main.js, src/pages/Main/Main.module.css, src/pages/commons/TopForm.js
topform의 로그인링크가 로그인시 형태가 로그아웃으로 바뀌게 되고 
로그아웃을 하면 로그인 및 회원가입으로 다시 바뀌게 되도록 수정하였습니다.
=> topform 로그인 로그아웃

src/pages/Home/OneRoom/List/List.js, src/pages/Home/OneRoom/OneRoom.js, src/pages/Home/OneRoom/OneRoom.module.css
모든 마커들의 정보들을 리스트에 출력하는 것에서
화면에 보이는 마커들의 정보들만 리스트에 출력하는 것으로 업데이트 됐습니다.
=> status of marker list

src/pages/Board/BoardContents/js/FreeBoardContents.js, src/pages/Board/BoardContents/js/RoomBoardContents.js, src/pages/Board/BoardContentsList/css/BoardList.module.css, src/pages/Board/BoardContentsList/css/FreeBoardList.module.css, src/pages/Board/BoardContentsList/css/RoomBoardList.module.css, src/pages/Board/BoardContentsList/js/FreeBoardList.js, src/pages/Board/BoardContentsList/js/RoomBoardList.js
=> NG-64 게시글 댓글 목록 불러오기 

src/pages/SignUp/SignUp.js
=> NG-66 idduplcheck create

src/pages/Board/BoardContents/css/BoardContents.module.css, src/pages/Board/BoardContents/js/FreeBoardContents.js, src/pages/Board/BoardContents/js/RoomBoardContents.js
=> NG-65 댓글 수정 기능

src/pages/commons/TopForm.js, src/pages/commons/TopForm.module.css
topform에 마이페이지로 가는 버튼이 추가되었습니다.
=> topform 마이페이지 경로추가

package-lock.json, package.json, src/pages/Admin/MemberManagement.js, src/pages/Admin/SideBar.js, src/pages/Enrollment/HomeEnrollment.js
회원리스트를 보여주는거와 삭제기능을 만들었습니다.
npm install을 해주었습니다.
SideBar는 link를 잘못걸어서 고쳤습니다.
HomeEnrollment는 api테스트 하기 위해 추가만 해놓고 이게 테스트 중입니다.
=> NG-76 회원관리 추가

src/App.js, src/pages/Login/FindId/FindId.js, src/pages/Login/FindId/FindId.module.css, src/pages/Login/FindPw/FindPw.js, src/pages/Login/FindPw/FindPw.module.css, src/pages/Login/Login.js, src/pages/commons/TopForm.js
이제 로그인 페이지에서 아이디 비밀번호찾기를 클릭하면 해당 페이지로 이동합니다.
=> 아이디 비밀번호 찾기 페이지 추가

src/pages/Login/FindId/FindId.js, src/pages/Login/FindId/FindId.module.css, src/pages/Main/Main.module.css
axios를 통해 이메일을 보내 서버로부터 아이디를 받아오는 기능을 추가했습니다.
=> 이메일로 아이디 불러오기

src/pages/MyPage/MyPage.js, src/pages/MyPage/MyPage.module.css
=> NG-27 mypage update

src/pages/EstateManage/EstateInsert/js/EstateInsert1.js, src/pages/EstateManage/EstateInsert/js/EstateInsert2.js, src/pages/EstateManage/EstateInsert/js/EstateInsert3.js
필수 항목 입력 안 했을 경우,
이미지를 3장 이상 10장 이하로 올리지 않았을 경우에
대한 유효성 검사가 추가되었습니다
=> 유효성 검사 로직 추가

src/pages/Admin/Admin.module.css, src/pages/Admin/AdminMain.js, src/pages/Admin/AgentManagement.js
=> NG-56 공인중개사 수정

src/pages/Main/Main.js
문제가 매일 업데이트가 되지 않아 수정을 했습니다 매일 자정에 visited를 초기화 시켜 매일 데이터를 업데이트가 되도록 수정하였습니다.
=> NG-85 조회수 수정

src/pages/Enrollment/HomeEnrollment.js, src/pages/SignUp/SignUp.js
회원등록이 되면 신규회원이 몇 명이 되는지 알 수 있게 만들었습니다. HomeEnrollment.js는 아직 테스트 중입니다.
=> NG-85 신규 등록 수 추가

src/pages/Admin/Admin.module.css, src/pages/Admin/AgentManagement.js, src/pages/Admin/MemberManagement.js, src/pages/Main/Main.js
=> NG-56 공인중개사 table 수정

src/pages/MyPage/DeleteMyInfo.js, src/pages/MyPage/MyPage.js, src/pages/MyPage/css/DeleteMyInfo.module.css, src/pages/MyPage/css/MyPage.module.css
=> NG-27 mypage & deleteMyInfo update

src/pages/MyPage/UpdateMyInfo.js, src/pages/SignUp/SignUp.js, src/pages/commons/TopForm.js
마이페이지에서 로그아웃 시 오류나는 부분 수정했습니다.
회원가입과 회원정보 수정에 이용되는 kakao postcode api 모달창 ui 수정했습니다.
=> logout & kakao postcode api modal fixed

src/pages/Board/Write/js/WriteBoard/FreeBoardWrite.js, src/pages/Board/Write/js/WriteBoard/RoomBoardWrite.js
=> NG-70 게시판 글 작성 기능 ( 파일 포함 )

src/pages/MyPage/ChangePw.js, src/pages/MyPage/MyPage.js, src/pages/MyPage/css/ChangePw.module.css
=> NG-93 changePw create

src/pages/EstateManage/EstateBoard/js/EstateBoard.js
=> 매물 게시판 - 임시

src/pages/MyPage/MyPage.js, src/pages/MyPage/css/MyPage.module.css
=> NG-95 mypage css update

public/index.html, src/pages/Home/OneRoom/OneRoom.js
홈(집) 업데이트 됐습니다.
우선 예제로 DB에 있는 정보들 불러오고 콘솔에 출력하는 거랑
클러스터링 기능 추가 됐습니다.
=> map clusterer update

src/pages/Login/FindId/FindId.js, src/pages/Login/FindId/FindId.module.css, src/pages/Login/FindPw/FindPw.js, src/pages/Login/FindPw/FindPw.module.css
비밀번호 찾기 페이지가 구현되었습니다.
이메일 유효성 검사로 올바른 형식일 경우에만 서버로 정보를 전송합니다.
=> findPw create

src/pages/EstateManage/EstateBoard/js/EstateBoard.js
=> 매물 삭제 기능 추가

src/pages/Login/Login.js
관리자 로그인을 위한 모달창 만들었습니다. ctrl+shift+h 하면 나옵니다.
=> admin login modal create

src/pages/EstateManage/EstateBoard/js/EstateBoard.js, src/pages/EstateManage/EstateInsert/js/EstateInsert1.js, src/pages/EstateManage/EstateInsert/js/EstateInsert3.js, src/pages/EstateManage/js/Post.js
매물 등록시 주소2를 추가
DB도 변경
파일 올릴 때 이미지만 가능하도록 변경
=> 주소2 추가 / 파일 이미지만 가능

src/pages/Admin/Admin.module.css, src/pages/Admin/AgentManagement.js, src/pages/Admin/MemberManagement.js, src/pages/Enrollment/Enrollment.module.css, src/pages/Enrollment/HomeEnrollment.js
regex를 넣었고 입력안되면 가입이 안되게 만들었습니다.
=> NG-107 공인중개사 등록 수정

src/pages/Main/Main.js, src/pages/Main/Main.module.css, src/pages/commons/Footer.js, src/pages/commons/Footer.module.css
Main페이지에 있던 Footer를 공용으로 사용하기 위해 commons 파일안에 새로 생성했습니다.
=> Footer create

src/pages/Enrollment/Entry.js, src/pages/Enrollment/HomeEnrollment.js
Entry.js는 ui변경했고 
HomeEnrollment.js는 중복 검사로직을 구현했습니다.
=> NG-107 중개사무소 등록 수정

src/App.js, src/pages/Login/Login.js, src/pages/Login/Login.module.css, src/pages/commons/TopForm.js
관리자 로그인 만들고 스프링 시큐리티로 관리자 데이터 못넘어오게 막았습니다.
추가로 app.js에서 로그인 안할 시 마이페이지 이동 막았고, 관리자가 아닐 시 관리자 페이지 이동 막았습니다.
=> NG-106 admin login create & spring security update

src/pages/Admin/Admin.js, src/pages/Admin/AdminCRUD.js, src/pages/Admin/SideBar.js, src/pages/commons/TopForm.js
=> admin topform update

src/pages/EstateManage/EstateInsert/js/EstateInsert.js, src/pages/EstateManage/EstateInsert/js/EstateInsert1.js, src/pages/EstateManage/EstateInsert/js/EstateInsert2.js, src/pages/EstateManage/EstateInsert/js/EstateInsert3.js, src/pages/EstateManage/js/EstateManage.js
=> 매물 등록 페이지 통합

src/pages/Admin/Admin.js, src/pages/Admin/AdminCRUD.js, src/pages/Admin/SideBar.js, src/pages/Login/Login.js, src/pages/Login/Login.module.css
관리자 로그인 화면 ui 수정했습니다.
관리자 계정 등록, 삭제 ui 만들었다가 다시 삭제했습니다.
=> NG-110 admin login css update

src/pages/Board/BoardContentsList/css/FavoriteBoardList.module.css, src/pages/Board/BoardContentsList/js/FavoriteBoardList.js, src/pages/Board/BoardContentsList/js/FreeBoardList.js
=> NG-72 즐겨찾기 기능 

src/pages/Admin/AdminMain.js, src/pages/Admin/MemberManagement.js, src/pages/Enrollment/HomeEnrollment.js
AdminMain.js여기서는 공인중개사 차트로 보여주는 코드를 만들었고 그리고 실시간으로 5초간격으로 데이터를 업데이트 하는 코드를 만들었습니다. 
MemberManagement이거는 회원목록을 가져올 때 원래 membercontroller에서 가져왔는데 admin으로 옮겨서 경로를 새로 만들었습니다.
=> NG-85 메인페이지 & 회원관리 수정

src/pages/Admin/AdminMain.js
신규회원과 공인중개사의 각각 차트로 누적수와 오늘 신규회원수를 만들었습니다.
=> NG-85 관리자 메인페이지 수정

src/pages/Board/Board.js, src/pages/Board/BoardContents/js/FreeBoardContents.js, src/pages/Board/BoardContents/js/RoomBoardContents.js, src/pages/Board/BoardContentsList/css/FavoriteBoardList.module.css, src/pages/Board/BoardContentsList/js/FavoriteBoardList.js, src/pages/Board/BoardContentsList/js/FreeBoardList.js, src/pages/Board/BoardContentsList/js/RoomBoardList.js
게시글 검색 ( 제목 , 말머리 , 내용 ) 기능 추가
=> NG-71 게시글 검색 기능 추가

src/pages/Login/FindId/FindId.js, src/pages/Main/Main.js, src/pages/Main/Main.module.css
=> mainpage ui update

src/pages/Board/BoardContents/js/FreeBoardContents.js, src/pages/Board/BoardContents/js/RoomBoardContents.js, src/pages/Board/BoardContentsList/js/FavoriteBoardList.js
=> NG-92 게시글 파일 다운로드 기능

src/pages/Main/Main.js, src/pages/Main/Main.module.css
=> mainpage update

src/pages/Board/BoardContentsList/js/FavoriteBoardList.js, src/pages/Board/BoardContentsList/js/FreeBoardList.js, src/pages/Board/BoardContentsList/js/RoomBoardList.js
- 게시글 검색 기능
- 카테고리 선택 시 해당 게시글 목록 띄우기
=> NG-71 게시글 검색 기능

src/pages/Login/Login.js, src/pages/Login/Login.module.css
=> NG-115 estate login create

src/App.js, src/pages/Board/Board.js, src/pages/Board/BoardContents/js/FreeBoardContents.js, src/pages/Board/BoardContents/js/RoomBoardContents.js, src/pages/Board/Write/js/WriteBoard/FreeBoardWrite.js, src/pages/Board/Write/js/WriteBoard/RoomBoardWrite.js
- 자신의 글 또는 관리자 계정일 때 수정 / 삭제 버튼 뜨도록 막음
- 게시글에서 로그아웃 하면 발생하는 오류 수정
=> NG-78 댓글,게시물 수정/삭제 권한

src/pages/Login/Login.js, src/pages/MyPage/ChangePw.js, src/pages/MyPage/DeleteMyInfo.js, src/pages/MyPage/MyPage.js, src/pages/MyPage/css/MyPage.module.css, src/pages/commons/TopForm.js
공인중개사 마이페이지에서 정보 띄우기, 회원탈퇴, 비밀번호 변경 기능 완성했습니다.
=> NG-118 estate mypage read&delete&pwupdate

src/App.js, src/pages/Review/Edit/EditReview.js, src/pages/Review/Edit/EditReview.module.css, src/pages/Review/Review.js, src/pages/Review/Write/WriteReview.js, src/pages/Review/Write/WriteReview.module.css
=> NG-144 리뷰 페이지 폴더 추가

src/pages/MyPage/MyPage.js, src/pages/MyPage/UpdateMyInfo.js, src/pages/MyPage/css/MyPage.module.css
공인중개사 회원정보 수정 기능 완료했습니다.
마이페이지 ui 일부 수정했습니다.
=> NG-119 estate Info update

src/pages/EstateAgent/ReviewApproval/js/ReviewApproval.js, src/pages/EstateAgent/js/EstateAgent.js, src/pages/EstateManage/EstateBoard/css/EstateBoard.module.css, src/pages/EstateManage/EstateBoard/js/EstateBoard.js, src/pages/EstateManage/EstateInsert/js/EstateInsert.js, src/pages/EstateManage/EstateUpdate/js/EstateUpdate.js, src/pages/EstateManage/EstateUpdate/js/EstateUpdate1.js, src/pages/EstateManage/EstateUpdate/js/EstateUpdate3.js
매물 등록시 아이디 정보 추가
매물 관리 페이지 페이지네이션 추가
매물 수정 페이지  출력시 초기값 추가
리뷰 권한을 부여할 공인중개사 페이지 추가중
=> 매물 등록 기타 등등

src/pages/MyPage/MyPage.js
=> NG-120 myreview read

src/pages/MyPage/MyPage.js
마이페이지에 내가 본 방에 대한 정보 띄우기 1차로 완성했습니다.
=> NG-120 mypage estate read

src/pages/MyPage/MyPage.js
마이페이지에 내가 본 방에 대한 정보 가져오고, 리뷰 권한 버튼 생성했습니다.
=> NG-120 mypage myreview update

src/pages/Home/OneRoom/Info/Info.js, src/pages/Review/Edit/EditReview.js
=> info.js state 전달 값 수정

src/pages/Home/OneRoom/OneRoom.js
=> subway add

src/pages/Admin/SideBar.js, src/pages/Admin/SideBar.module.css
=> 관리자 사이드바 ui 수정

src/pages/MyPage/MyPage.js, src/pages/MyPage/css/MyPage.module.css
마이페이지에 내가 본 방 띄우고, 권한에 따라 리뷰 쓰기 버튼 추가했습니다.
=> NG-120 mypage sawEstate update

src/pages/Enrollment/Enrollment.module.css, src/pages/Enrollment/HomeEnrollment.js
input태그로 css를 만들었는데 classname을 줘서 다시 만들었습니다.
=> 공인중개사 등록 css수정

src/pages/Login/Login.js, src/pages/MyPage/UpdateMyInfo.js
로그인 엔터기능 추가 했습니다.
공인중개사 회원정보 수정기능에 위도 경도 기능 추가했습니다.
=> NG-119 estate myInfo update

src/pages/MyPage/MyPage.js
console.log 제거하고 approval Code 업데이트 된 부분 마이페이지에 반영했습니다.
=> console.log delete & approvalCode update

src/pages/Admin/Admin.module.css, src/pages/Admin/NotificationManagement.js
=> NG-130 관리자리뷰관리 추가

src/pages/Home/OneRoom/OneRoom.js, src/pages/Home/OneRoom/RangeSlider.css, src/pages/Home/OneRoom/SliderToggle.css, src/pages/Home/OneRoom/newOneRoom/OneRoom.js, src/pages/Home/OneRoom/newOneRoom/OneRoom.module.css, src/pages/Home/OneRoom/newOneRoom/newandNew/OneRoom.module.css
필터 업데이트 했습니다.
기본 디자인 틀 추가 했고
월세 드레그 바에 따라서 가격 조정되게 바꿨습니다.
=> map filter update

src/pages/MyPage/MyPage.js
- 마이페이지에서 리뷰 작성 창으로 이동할 수 있도록 연결
=> NG-132 마이페이지와 리뷰작성 연결

src/pages/Admin/NotificationManagement.js
=> NG-130 리뷰관리 수정

src/pages/Login/Login.js
로그인 할 때 아이디와 비밀번호 틀리면 alert창 띄우도록 만들었습니다.
=> NG-25 login update

src/pages/Home/OneRoom/List/List.js, src/pages/Main/Main.js
=> 최근 본 매물 불러오기 추가

src/pages/Main/Main.js
전체 목록을 불러오는 것에서 6개만 불러오는것으로 url이 수정되었습니다.
=> 게시글 목록 불러오기 수정

src/pages/Review/Review.module.css, src/pages/Review/Write/WriteReview.js, src/pages/Review/Write/WriteReview.module.css
=> NG-128 리뷰 작성창 css 수정

src/pages/Main/Main.js
등록된 매물 전체를 불러오는 것에서 6개만 불러오도록 수정하였습니다.
=> 등록된 매물 불러오기 수정

src/pages/Board/BoardContents/js/RoomBoardContents.js, src/pages/Board/EditBoardContents/js/EditFreeBoardContents.js, src/pages/Board/EditBoardContents/js/EditRoomBoardContents.js, src/pages/Board/Write/js/WriteBoard/FreeBoardWrite.js, src/pages/Board/Write/js/WriteBoard/RoomBoardWrite.js
게시글 등록 / 수정 시 input에 파일 계속 들어가는 오류 발생한거 수정
=> NG-138 게시글 등록 / 수정 파일 버그

src/App.js, src/pages/Login/FindId/FindenrollmentId.js, src/pages/Login/FindPw/FindenrollmentPw.js, src/pages/Login/Login.js, src/pages/Main/Main.js, src/pages/Main/Main.module.css
공인중개사 아이디 비밀번호 파일이 추가되었습니다.
app.js에서 공인중개사 아이디 비밀번호로 가는 경로가 추가되었습니다.
=> 중개사 아이디 비밀번호 찾기 경로 추가

src/pages/MyPage/ChangePw.js, src/pages/MyPage/DeleteMyInfo.js, src/pages/MyPage/MyPage.js, src/pages/MyPage/UpdateMyInfo.js, src/pages/MyPage/css/ChangePw.module.css, src/pages/MyPage/css/DeleteMyInfo.module.css, src/pages/MyPage/css/MyPage.module.css, src/pages/MyPage/css/UpdateMyInfo.module.css
마이페이지 오류 수정하고 폰트 등 css 수정했습니다.
=> NG-27 mypage fixed

src/pages/Home/OneRoom/OneRoom.js, src/pages/Home/OneRoom/OneRoom.module.css
=> map move add by subway

src/pages/Home/OneRoom/OneRoom.js
지역, 대학교, 역
전부 이동 가능하게 바뀌었습니다 .
=> map move add by all

src/pages/Login/Login.js, src/pages/MyPage/MyPage.js, src/pages/MyPage/css/MyPage.module.css
로그인 placeholder 한글로 변경하고,
마이페이지에 로딩창 추가했습니다.
=> NG-95 login&mypage css update

package-lock.json, package.json, src/pages/Login/Login.js, src/pages/MyPage/ChangePw.js, src/pages/MyPage/DeleteMyInfo.js, src/pages/MyPage/UpdateMyInfo.js, src/pages/SignUp/SignUp.js
마이페이지, 로그인, 회원가입에 sweetalert 적용했습니다. npm install 필요
=> sweetalert update

src/pages/SignUp/SignUp.js, src/pages/SignUp/SignUp.module.css
=> NG-77 signup css update

src/pages/Login/FindId/FindenrollmentId.js, src/pages/Main/Main.js
중개사 아이디 찾기 기능이 추가되었습니다.
최근 본 매물이 없다면 없다는 문구가 출력됩니다.
=> 중개사 아이디 찿기 추가

src/pages/Main/Main.module.css
span 태그에 css를 줘서 전체에 적용되는걸 수정했습니다.
=> main css 수정

src/pages/Home/OneRoom/Info/Info.js, src/pages/Home/OneRoom/Info/Info.module.css, src/pages/Home/OneRoom/List/List.js, src/pages/Home/OneRoom/OneRoom.js, src/pages/Home/OneRoom/OneRoom.module.css
아까 한건지 지금 한건지 정확하게 기억은 안 나는데 일단 혹시 모르니까 적을께용.
일단 지도가 그동안 드레그, 확대, 축소 이벤트에서는
오른쪽에 표기되는 리스트를 제대로 받아왔는데
필터링이나, 첫 화면 오픈때는 맵 인자를 받아올 수가 없어
제대로 못 받아오는 상황이 발생해서 
바운스(대충 지도 경계선 그리는거) 가져올수가 없으면
역으로 인자 참조하게 수정해서 해당 오류 수정 했습니다.
나머지는 리스트 나오는 내용들 본격 업데이트 시작 했습니다.
일단 리스트에 나올 것들 폼은 전부 잡았고 디자인도 수정 해놨습니다.
=> 매너온도 업데이트, 지도 버그 수정

src/pages/Login/Login.js, src/pages/Review/Edit/EditReview.js, src/pages/Review/Write/WriteReview.js
리뷰 작성 수정 로그인 안하고 들어갈 시 권한 없다는 alert창 띄웠습니다.
=> NG-117 review update

src/pages/Login/FindId/FindId.js, src/pages/Login/FindId/FindId.module.css, src/pages/Login/FindId/FindenrollmentId.js, src/pages/Login/FindPw/FindPw.js, src/pages/Login/FindPw/FindPw.module.css, src/pages/Login/FindPw/FindenrollmentPw.js, src/pages/Main/Main.js, src/pages/Main/Main.module.css, src/pages/commons/TopForm.js
- 중개사 로그인시 중개사무소 가입 버튼 출력되는 오류를 수정했습니다.
- 최근 본 매물 css 수정했습니다.
- 메인페이지 콘솔창에 key값을 주지않아 발생하는 오류를 수정했습니다.
- 중개사 비밀번호 찾기 기능 추가했습니다.
- 아이디,비밀번호 찾기 ui 수정했습니다.
=> 중개사 비밀번호 기능 추가

src/pages/MyPage/MyPage.js, src/pages/Review/Write/WriteReview.js
approvalCode 에 a5 추가해서 리뷰 한 번 쓰면 내가 쓴 리뷰로 가기 버튼 뜨도록 만들었습니다.
=> mypage review update

src/pages/commons/TopForm.js
topform에서 게시판 경로를 추가했습니다.
원룸의 방내놓기 찜한매물로 가는 경로를 삭제했습니다.
=> topform 경로 수정

src/pages/MyPage/MyPage.js
크로스 체킹을 위해 리뷰 작성 완료 시 리뷰 보러 가기 버튼 대신 리뷰 작성 완료 버튼을 띄웠습니다.
=> mypage update

src/pages/Home/OneRoom/Info/Info.js, src/pages/Home/OneRoom/Info/Info.module.css, src/pages/Home/OneRoom/List/List.js, src/pages/Home/OneRoom/List/List.module.css, src/pages/Home/OneRoom/OneRoom.js
지도 이동 할때
한번이라도 줌, 드래그 이벤트 발생 되면
이상한 곳으로 이동하는게 있어서
이동시키는 로직 수정 했습니다.
리스트랑 정보에 가져오는 
이미지도 나오게 수정 했습니다.
매너온도 45도 이상만 추천하게 바꿨습니다
=> 지도 이동 버그 수정, 리스트 이미지 삽입, 정보 이미지 삽입, 매너 온도 수정

src/pages/Board/Board.js, src/pages/Board/BoardContents/js/FreeBoardContents.js, src/pages/Board/BoardContents/js/RoomBoardContents.js, src/pages/Board/BoardContentsList/js/FavoriteBoardList.js, src/pages/Board/BoardContentsList/js/FreeBoardList.js, src/pages/Board/EditBoardContents/js/EditFreeBoardContents.js, src/pages/Board/EditBoardContents/js/EditRoomBoardContents.js, src/pages/Board/Write/js/WriteBoard/FreeBoardWrite.js, src/pages/Board/Write/js/WriteBoard/RoomBoardWrite.js, src/pages/Board/commons_js/alert.js, src/pages/Review/Write/WriteReview.js
=> sweetalert 적용중

package-lock.json, package.json, src/pages/Admin/Admin.js, src/pages/Admin/Admin.module.css, src/pages/Admin/AdminDashboard.js, src/pages/Admin/AdminDashboard.module.css, src/pages/Admin/AgentManagement.js, src/pages/Admin/MemberManagement.js, src/pages/Admin/SideBar.js, src/pages/Admin/SideBar.module.css, src/pages/Admin/statics/RoomStatics.js, src/pages/Enrollment/HomeEnrollment.js
nivo 차트 install했습니다.
SideBar.js는 아직 미완성이고 AdminDashboard.js이게 대시보드입니다 나중에 원래 있던 메인페이지를 없애고 저걸로 할거에요
RoomStatics.js이거는 차트 따로 만들어서 대시보드에 가져옵니다.
=> NG-85 관리자 대시보드 수정

src/pages/Login/FindId/FindId.js, src/pages/Login/FindPw/FindPw.js
아이디, 비밀번호 찾기에 sweetalert 적용하고 console.log 제거했습니다.
=> FindId & FindPw update

src/pages/Login/FindId/FindId.module.css, src/pages/Login/FindId/FindenrollmentId.js, src/pages/Login/FindPw/FindPw.module.css, src/pages/Login/FindPw/FindenrollmentPw.js, src/pages/Login/Login.module.css, src/pages/MyPage/ChangePw.js, src/pages/MyPage/DeleteMyInfo.js, src/pages/MyPage/UpdateMyInfo.js, src/pages/MyPage/css/ChangePw.module.css, src/pages/MyPage/css/DeleteMyInfo.module.css, src/pages/MyPage/css/UpdateMyInfo.module.css, src/pages/SignUp/SignUp.module.css
아이디, 비밀번호 찾기에 sweetalert 적용했습니다.
마이페이지, 로그인, 회원가입 input css 수정했습니다.
=> mypage & FindId & FindPW css update

src/pages/Login/Login.js, src/pages/Login/Login.module.css, src/pages/MyPage/MyPage.js, src/pages/MyPage/css/MyPage.module.css
=> css update

src/pages/SignUp/SignUp.js
=> signup footer added

src/pages/MyPage/MyPage.js
=> mypage fixed

src/App.js, src/pages/EstateManage/ReviewApproval/js/ReviewApproval.js
=> 공인중개사 받은 문의 전화번호 출력

src/pages/Login/FindId/FindId.js, src/pages/Login/FindId/FindenrollmentId.js, src/pages/Login/FindPw/FindPw.js, src/pages/Login/FindPw/FindenrollmentPw.js, src/pages/Login/Login.js, src/pages/MyPage/ChangePw.js, src/pages/MyPage/DeleteMyInfo.js, src/pages/MyPage/MyPage.js, src/pages/MyPage/UpdateMyInfo.js, src/pages/MyPage/css/MyPage.module.css, src/pages/MyPage/css/UpdateMyInfo.module.css, src/pages/SignUp/SignUp.js
sweet alert, 몇몇 오류, console.log 제거했습니다.
=> sweet alert delete

src/pages/MyPage/MyPage.js, src/pages/MyPage/css/MyPage.module.css
마이페이지에 내가 본 방, 내 신고 목록 css 수정했습니다.
=> mypage css update

src/pages/Home/OneRoom/Info/Info.js, src/pages/Home/OneRoom/OneRoom.js, src/pages/Home/OneRoom/OneRoom.module.css, src/pages/Review/Board/ReviewBoard.js
리뷰 게시판으로 데이터 넘기기랑 (아직 제대로안넘어감)
로그인 안 하고 신고하기 눌렀을때 화면,
필터에서 zindex 너무 높아서 모달 중첩되는거 수정 했습니다.
=> map update

src/pages/Login/Login.js, src/pages/MyPage/MyPage.js
=> admin login input css update

src/pages/EstateManage/css/EstateManage.module.css, src/pages/EstateManage/css/SideBar.module.css, src/pages/EstateManage/js/SideBar.js
=> css modified

src/pages/Main/Main.js, src/pages/Main/Main.module.css
이미지 경로에 }가 추가된 오류를 수정했습니다.
이미지의 css를 수정했습니다
=> 최근 본 매물 경로 수정

src/pages/Board/EditBoardContents/js/EditFreeBoardContents.js, src/pages/Board/EditBoardContents/js/EditRoomBoardContents.js, src/pages/Board/Write/js/WriteBoard/FreeBoardWrite.js, src/pages/Board/Write/js/WriteBoard/RoomBoardWrite.js, src/pages/Review/Board/ReviewBoard/ReviewBoard.js
=> 리액트퀼 이미지 첨부 오류 수정

src/pages/MyPage/MyPage.js, src/pages/MyPage/UpdateMyInfo.js, src/pages/MyPage/css/MyPage.module.css, src/pages/MyPage/css/UpdateMyInfo.module.css, src/pages/SignUp/SignUp.js
공인중개사 마이페이지에 공인중개사 소개글 추가했습니다.
=> estate mypage content update

src/pages/Home/OneRoom/OneRoom.js, src/pages/Main/Main.js
최근 본 매물, 등록된 매물, 검색 시 클릭한 매물의 위치로 이동합니다
=> 메인페이지에서 지도로 이동 추가

src/pages/Login/Login.module.css, src/pages/MyPage/css/ChangePw.module.css, src/pages/MyPage/css/DeleteMyInfo.module.css, src/pages/MyPage/css/UpdateMyInfo.module.css, src/pages/SignUp/SignUp.module.css, src/pages/find/FindId.module.css, src/pages/find/FindPw.module.css, src/pages/find/FindenrollmentPw.js
=> input css update

src/pages/MyPage/MyPage.js, src/pages/MyPage/UpdateMyInfo.js, src/pages/SignUp/SignUp.js
버튼 안에 들어가는 내용 길어서 깨지는 부분 수정했습니다.
=> button css update

src/pages/Login/Login.module.css
=> admin login button css update

src/pages/Board/Board.js, src/pages/Board/BoardContents/js/FreeBoardContents.js, src/pages/Board/BoardContents/js/RoomBoardContents.js, src/pages/Board/BoardContentsList/js/FavoriteBoardList.js, src/pages/Board/BoardContentsList/js/FreeBoardList.js, src/pages/Board/BoardContentsList/js/RoomBoardList.js, src/pages/Board/EditBoardContents/js/EditFreeBoardContents.js, src/pages/Board/EditBoardContents/js/EditRoomBoardContents.js, src/pages/Board/Write/js/WriteBoard/FreeBoardWrite.js, src/pages/Board/Write/js/WriteBoard/RoomBoardWrite.js, src/pages/Review/Edit/EditReview.js, src/pages/Review/ReviewBoardContents/ReviewBoardContents.js, src/pages/Review/Write/WriteReview.js
gcs 적용으로 파일 경로 바꿔줌, 양도게시판 글 수정 오류 ( 첨부 파일 목록 안뜨는거 ) 수정
=> gcs 적용으로 파일 경로 바꿔줌

src/pages/Board/Board.js, src/pages/Board/Board.module.css, src/pages/Board/BoardContents/css/BoardContents.module.css, src/pages/Board/BoardContents/js/FreeBoardContents.js, src/pages/Board/BoardContents/js/RoomBoardContents.js, src/pages/Board/EditBoardContents/js/EditFreeBoardContents.js, src/pages/Board/EditBoardContents/js/EditRoomBoardContents.js, src/pages/Board/Write/js/WriteBoard/FreeBoardWrite.js, src/pages/Board/Write/js/WriteBoard/RoomBoardWrite.js, src/pages/Review/Edit/EditReview.js, src/pages/Review/Review.js, src/pages/Review/Review.module.css, src/pages/Review/ReviewBoard/ReviewBoard.js, src/pages/Review/ReviewBoard/ReviewBoard.module.css, src/pages/Review/ReviewBoardContents/ReviewBoardContents.js, src/pages/Review/Write/WriteReview.js
오류 수정 
css 폰트 수정
console.log 삭제
=> 오류 , css, console.log

src/pages/Board/Board.module.css, src/pages/Review/Review.module.css
=> style 폰트 수정

public/index.html, src/pages/Login/Login.js, src/pages/MyPage/MyPage.js, src/pages/MyPage/UpdateMyInfo.js, src/pages/MyPage/css/UpdateMyInfo.module.css
중개사 전화번호 수정 로직 고쳤습니다.
중개사 로그인 시 승인되지 않은 회원에게 띄우는 alert창 수정했습니다.
=> 중개사 전화번호 수정

public/index.html, src/pages/Home/OneRoom/Info/Info.js, src/pages/Home/OneRoom/Info/Info.module.css, src/pages/Home/OneRoom/List/List.js, src/pages/Home/OneRoom/OneRoom.js
=> 지도 (홈) 1차 종료

src/pages/Login/Login.js
=> login update

src/pages/Home/OneRoom/Info/Info.js, src/pages/Main/Main.js
info에서 이미지 클릭시 로컬 스토리지에 값이 추가됩니다.
=> 로컬 스토리지 값 추가

src/pages/Board/BoardContents/js/FreeBoardContents.js, src/pages/Board/BoardContents/js/RoomBoardContents.js, src/pages/Board/BoardContentsList/js/FavoriteBoardList.js, src/pages/Board/BoardContentsList/js/FreeBoardList.js, src/pages/Board/BoardContentsList/js/RoomBoardList.js, src/pages/Board/EditBoardContents/js/EditFreeBoardContents.js, src/pages/Board/EditBoardContents/js/EditRoomBoardContents.js, src/pages/Board/Write/js/WriteBoard/FreeBoardWrite.js, src/pages/Board/Write/js/WriteBoard/RoomBoardWrite.js, src/pages/Review/Edit/EditReview.js, src/pages/Review/ReviewBoard/ReviewBoard.js, src/pages/Review/ReviewBoardContents/ReviewBoardContents.js, src/pages/Review/Write/WriteReview.js
=> console.log 삭제

src/pages/MyPage/UpdateMyInfo.js, src/pages/SignUp/SignUp.js
=> console.log delete

src/pages/MyPage/MyPage.js
=> mypage estateImage link fixed

src/pages/Main/Main.js, src/pages/find/FindenrollmentPw.js
=> 이미지 url 수정

src/pages/EstateManage/EstateInsert/js/EstateInsert1.js, src/pages/EstateManage/EstateUpdate/js/EstateUpdate1.js
=> bug modified

src/pages/Main/Main.js, src/pages/Main/Main.module.css, src/pages/commons/TopForm.js
원룸에서 topform의 투룸 오피스텔을 누르면 값이 날라가던 오류를 수정했습니다
=> topform 오류 수정

src/pages/Main/Main.js, src/pages/commons/TopForm.js
=> ㅁmain 오류 수정

src/pages/Board/Write/js/WriteBoard/FreeBoardWrite.js, src/pages/Board/Write/js/WriteBoard/RoomBoardWrite.js, src/pages/Home/OneRoom/Info/Info.js
=> info.js 익명 수정

src/pages/Review/Write/WriteReview.js
=> 리뷰작성 오류 수정

public/index.html, src/pages/Home/OneRoom/Info/Info.js
=> 홈 (지도) 이미지 순서 설정
